
struct _ylib_namespace y = {
	.sys = {
		.malloc = _ymalloc,
		.calloc = _ycalloc,
		.free = _yfree
	},
	.str = {
		.create = _ys_new,
		.free = _ys_free,
		.trunc = _ys_trunc,
		.setsz = _ys_setsz,
		.len = _ys_len,
		.append = _ys_append,
		.prepend = _ys_prepend,
		.nappend = _ys_nappend,
		.nprepend = _ys_nprepend,
		.dup = _ys_dup,
		.tostring = _ys_string,
		.concat = _ys_concat,
		.ltrim = _ys_ltrim,
		.rtrim = _ys_rtrim,
		.trim = _ys_trim,
		.lshift = _ys_lshift,
		.rshift = _ys_rshift,
		.putc = _ys_putc,
		.addc = _ys_addc,
		.upcase = _ys_upcase,
		.lowcase = _ys_lowcase,
		.printf = _ys_printf,
		.vprintf = _ys_vprintf,
		.str2hexa = _ys_str2hexa,
		.subs = _ys_subs,
		.casesubs = _ys_casesubs,
		.str2xmlentity = _str2xmlentity,
		.xmlentity2str = _xmlentity2str
	},
	.vect = {
		.create = _yv_create,
		.free = _yv_free,
		.trunc = _yv_trunc,
		.setsz = _yv_setsz,
		.len = _yv_len,
		.cat = _yv_cat,
		.ncat = _yv_ncat,
		.dup = _yv_dup,
		.concat = _yv_concat,
		.put = _yv_put,
		.add = _yv_add,
		.ins = _yv_ins,
		.pop = _yv_pop,
		.get = _yv_get,
		.ext = _yv_ext,
		.uniq = _yv_uniq,
		.sort = _yv_sort,
		.search = _yv_search,
		.foreach = _yv_foreach
	},
	.map = {
		.create = _ymap_create,
		.free = _ymap_free,
		.add = _ymap_add,
		.search = _ymap_search,
		.searchElement = _ymap_search_element,
		.remove = _ymap_remove,
		.resize = _ymap_resize,
		.foreach = _ymap_foreach
	}
};

